### ISSUE TITLE
Can't set up Auto Scaling with Cluster resource

### ISSUE THREAD

**Issue by RushaliD12** [aws-quickstart/quickstart-mongodb-atlas#24]
Hi,

I'm having an issue creating an Atlas cluster with autoscaling enabled. Given the below resource definition, I get a 400 error with the message Compute auto-scaling min instance size required.. However, if I specify AutoScaling.Compute.MaxInstanceSize and/or AutoScaling.Compute.MinInstanceSize in my resource definition, I get another error saying Invalid attribute minInstanceSize specified. Is Cluster Tier scaling supported, and if so, do y'all have a working example? Thanks in advance.
**Code snippet**

 ```
 "OrganizerServicesTestInstanceAtlasClsutertestinstance543CDFC6": {
   "Type": "MongoDB::Atlas::Cluster",
   "Properties": {
    "ApiKeys": {
     "PublicKey": "<REDACTED>",
     "PrivateKey": "<REDACTED>"
    },
    "ProjectId": {
     "Ref": "OrganizerServicesAtlasProjectAtlasProjectsandboxE89594CB"
    },
    "Name": "test-instance",
    "MongoDBMajorVersion": "5.0",
    "ProviderSettings": {
     "BackingProviderName": "AWS",
     "InstanceSizeName": "M10",
     "RegionName": "us-east-1",
     "AutoScaling": {
      "Compute": {
       "Enabled": true,
       "ScaleDownEnabled": true,
       "MinInstanceSize": "M10",
       "MaxInstanceSize": "M50"
      }
     }
    },
    "AutoScaling": {
     "Compute": {
      "Enabled": true,
      "ScaleDownEnabled": true
     }
    }
   },
   "DependsOn": [
    "OrganizerServicesAtlasProjectAtlasProjectsandboxE89594CB"
   ],
   "Metadata": {
    "aws:cdk:path": "OrganizerServicesInfrastructureStack-sandbox/OrganizerServicesTestInstance/AtlasClsuter-test-instance"
   }
  },

```
**Expected Behavior**

200 response, cluster created with cluster tier scaling enabled.

**Actual behavior**

400, Compute auto-scaling min instance size required. if AutoScaling.Compute.MinInstanceSize is not set,
400, Invalid attribute minInstanceSize specified. if AutoScaling.Compute.MinInstanceSize is set.

**Comment by devopslondon2021** [comment]
+1 as I am also finding the autoscaling solution via CloudFormation. 

@RushaliD12, I noticed that `MinInstanceSize` and `MaxInstanceSize` are commented under [resources.go](https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/06e82a47c7c34a5b6fb491a06bb40f20af840170/cfn-resources/cluster/cmd/resource/resource.go#L161) the autoscaling section. Is that the reason why it is breaking? 

<img width="828" alt="image" src="https://user-images.githubusercontent.com/77589048/192856654-66027f76-0591-44a0-bac3-374fc78e924f.png">

**Comment by Zuhairahmed** [comment]
@devopslondon2021 @RushaliD12 we are currently refreshing our Quick Start, eta for publishing is in a few months. in the meantime feel free to pull down MongoDB::Atlas::Cluster resource directly from the Third Party CloudFormation Public Registry which as support for autoscaling. more details on this resource here:  https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Multi-Cloud-Clusters

**Comment by vsnyc** [comment]
This is no longer relevant, the Solution has been updated to use 3rd party CloudFormation Public Registry resources.
