### ISSUE TITLE
Create stack fail - resources "does not match service region eu-west-3"

### ISSUE THREAD

**Issue by gthibaud** [aws-quickstart/quickstart-mongodb-atlas#33]
Hello,

I'm trying to deploy "mongodb-atlas", following the QuickStart tutorial here: https://aws-quickstart.github.io/quickstart-mongodb-atlas/. Here are the parameters I use:

<img width="831" alt="parameters" src="https://user-images.githubusercontent.com/27550148/219482793-7b9e5541-a65f-41af-9008-58dcff176a8e.png">

However, the deployment fails when deploying extensions. The following screenshot shows the errors I receive (identical message for all extensions: Project, Cluster, DatabaseUser, ProjectIPAccessList, NetworkPeering):

<img width="1206" alt="errors" src="https://user-images.githubusercontent.com/27550148/219483395-beb2eaa4-6680-4561-a9b2-1ce6d0370a2c.png">

Could you tell me if the error is related to a bad parameters configuration?

Thank you very much for your help!

Best,
Grégoire

**Comment by Zuhairahmed** [comment]
Hi @gthibaud , thanks for your comment. There are a few possibilities that may cause this error which I have highlighted below. If these don’t unblock you directly, let me know and we can investigate further: 

1. Activate each of the above 3rd party extensions (i.e. MONGODB::ATLAS::PROJECT) in each AWS region and from each AWS account that you wish to deploy from (i.e. eu-west-3)
2. Ensure you have sufficiently strong AWS IAM Activation Role attached to this 3rd party extension. For sample IAM Role see [here](https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/cfn-resources/execute-role.template.yml)
3. Ensure your activated 3rd party public extension matches name exactly to default Atlas name (i.e. MONGODB::ATLAS::PROJECT). you may need to delete private extension if this namespace is already occupied.
4. Ensure your MongoDB Atlas Programmatic API Keys (PAKs) being used with CloudFormation have sufficiently strong permissions (Organization Project Creator or Organization Owner)
5. Ensure your MongoDB Atlas PAKs have correct IP Address / CIDR range access, for testing purposes you can with caution open keys to all access by adding “0.0.0.0/1” and “128.0.0.0/1”

Hope this helps!

**Comment by gthibaud** [comment]
Hi @Zuhairahmed, thank you very much for your response. 

I have carefully applied the steps you mentioned but I still get the error "ARN 'arn:aws:cloudformation:us-east-1::type/resource/bb989456c78c398a858fef18f2ca1bfc1fbba082/MongoDB-Atlas-Project' does not match service region eu-west-3" for each MongoDB third party extension (cf. screenshot).

<img width="1229" alt="Capture d’écran 2023-02-17 à 11 35 09" src="https://user-images.githubusercontent.com/27550148/219621408-9437fa52-7582-409b-acbc-f94c1f6bd1e7.png">

I am at your disposal if I can give you more information to investigate in depth.

Thank you!

Best,
Grégoire

**Comment by Zuhairahmed** [comment]
Thanks for sharing. We are in the process of refreshing this Partner Solutions deployment, updates should be up next week. Will let you know when ready to re-test again.

**Comment by Zuhairahmed** [comment]
hi @gthibaud Quick Start has been refreshed with more AWS Regions added! feel free to kick the tires today: https://aws.amazon.com/solutions/partners/mongodb-atlas/

**Comment by gthibaud** [comment]
Thank you! 😊

**Comment by gthibaud** [comment]
Thank you! 😊
